
const cards = [
    {
        cimg: "./../public/images/1.jpg",
        idimg: "./../public/images/heart.svg",
        cart: "./../public/images/cart.svg",
        ctit: "롤리팝-설탕봉지 에코백",
        percent: "10",
        won: "71,100",
        crate: 4.8,
        cdate: "30",
        rate_img: "./../public/images/star.svg" ,
        co_img: "./../public/images/co.svg",
    },
    {
        cimg: "./../public/images/5.jpg",
        idimg: "./../public/images/heart.svg",
        cart: "./../public/images/cart.svg",
        ctit: "펩티세라 주름 + 미백 기능서 아이크림 60ml",
        percent: "58",
        won: "17,800",
        crate: 4.0,
        cdate: "36",
        rate_img: "./../public/images/star.svg" ,
        co_img: "./../public/images/co.svg",
    },
    {
        cimg: "./../public/images/3.jpg",
        idimg: "./../public/images/heart.svg",
        cart: "./../public/images/cart.svg",
        ctit: "당일발송 재구매율1위_너에게 향하는 길 가죽시계",
        percent: "15",
        won: "32,300",
        crate: 3.8,
        cdate: "385",
        rate_img: "./../public/images/star.svg" ,
        co_img: "./../public/images/co.svg",
    },
    {
        cimg: "./../public/images/2.jpg",
        idimg: "./../public/images/heart.svg",
        cart: "./../public/images/cart.svg",
        ctit: "티닥인기 mini 티백 5종 모둠선물세트",
        percent: "16",
        won: "21,000",
        crate: 4.2,
        cdate: "9",
        rate_img: "./../public/images/star.svg" ,
        co_img: "./../public/images/co.svg",
    },
    {
        cimg: "./../public/images/4.jpg",
        idimg: "./../public/images/heart.svg",
        cart: "./../public/images/cart.svg",
        ctit: "흡토해도 좋은 촉촉 트린트먼트 앰플토너",
        percent: "32",
        won: "10,800",
        crate: 4.2,
        cdate: "21",
        rate_img: "./../public/images/star.svg" ,
        co_img: "./../public/images/co.svg",
    },
];
